module.bert.embeddings.word_embeddings.weight	True	0	1
module.bert.embeddings.position_embeddings.weight	True	0	1
module.bert.embeddings.token_type_embeddings.weight	True	0	1
module.bert.embeddings.LayerNorm.weight	True	0	1
module.bert.embeddings.LayerNorm.bias	True	0	1
module.bert.encoder.layer.0.attention.self.query.weight	True	0	1
module.bert.encoder.layer.0.attention.self.query.bias	True	0	1
module.bert.encoder.layer.0.attention.self.key.weight	True	0	1
module.bert.encoder.layer.0.attention.self.key.bias	True	0	1
module.bert.encoder.layer.0.attention.self.value.weight	True	0	1
module.bert.encoder.layer.0.attention.self.value.bias	True	0	1
module.bert.encoder.layer.0.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.0.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.0.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.0.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.0.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.0.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.0.output.dense.weight	True	0	1
module.bert.encoder.layer.0.output.dense.bias	True	0	1
module.bert.encoder.layer.0.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.0.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.1.attention.self.query.weight	True	0	1
module.bert.encoder.layer.1.attention.self.query.bias	True	0	1
module.bert.encoder.layer.1.attention.self.key.weight	True	0	1
module.bert.encoder.layer.1.attention.self.key.bias	True	0	1
module.bert.encoder.layer.1.attention.self.value.weight	True	0	1
module.bert.encoder.layer.1.attention.self.value.bias	True	0	1
module.bert.encoder.layer.1.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.1.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.1.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.1.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.1.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.1.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.1.output.dense.weight	True	0	1
module.bert.encoder.layer.1.output.dense.bias	True	0	1
module.bert.encoder.layer.1.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.1.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.2.attention.self.query.weight	True	0	1
module.bert.encoder.layer.2.attention.self.query.bias	True	0	1
module.bert.encoder.layer.2.attention.self.key.weight	True	0	1
module.bert.encoder.layer.2.attention.self.key.bias	True	0	1
module.bert.encoder.layer.2.attention.self.value.weight	True	0	1
module.bert.encoder.layer.2.attention.self.value.bias	True	0	1
module.bert.encoder.layer.2.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.2.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.2.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.2.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.2.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.2.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.2.output.dense.weight	True	0	1
module.bert.encoder.layer.2.output.dense.bias	True	0	1
module.bert.encoder.layer.2.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.2.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.3.attention.self.query.weight	True	0	1
module.bert.encoder.layer.3.attention.self.query.bias	True	0	1
module.bert.encoder.layer.3.attention.self.key.weight	True	0	1
module.bert.encoder.layer.3.attention.self.key.bias	True	0	1
module.bert.encoder.layer.3.attention.self.value.weight	True	0	1
module.bert.encoder.layer.3.attention.self.value.bias	True	0	1
module.bert.encoder.layer.3.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.3.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.3.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.3.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.3.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.3.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.3.output.dense.weight	True	0	1
module.bert.encoder.layer.3.output.dense.bias	True	0	1
module.bert.encoder.layer.3.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.3.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.4.attention.self.query.weight	True	0	1
module.bert.encoder.layer.4.attention.self.query.bias	True	0	1
module.bert.encoder.layer.4.attention.self.key.weight	True	0	1
module.bert.encoder.layer.4.attention.self.key.bias	True	0	1
module.bert.encoder.layer.4.attention.self.value.weight	True	0	1
module.bert.encoder.layer.4.attention.self.value.bias	True	0	1
module.bert.encoder.layer.4.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.4.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.4.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.4.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.4.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.4.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.4.output.dense.weight	True	0	1
module.bert.encoder.layer.4.output.dense.bias	True	0	1
module.bert.encoder.layer.4.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.4.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.5.attention.self.query.weight	True	0	1
module.bert.encoder.layer.5.attention.self.query.bias	True	0	1
module.bert.encoder.layer.5.attention.self.key.weight	True	0	1
module.bert.encoder.layer.5.attention.self.key.bias	True	0	1
module.bert.encoder.layer.5.attention.self.value.weight	True	0	1
module.bert.encoder.layer.5.attention.self.value.bias	True	0	1
module.bert.encoder.layer.5.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.5.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.5.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.5.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.5.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.5.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.5.output.dense.weight	True	0	1
module.bert.encoder.layer.5.output.dense.bias	True	0	1
module.bert.encoder.layer.5.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.5.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.6.attention.self.query.weight	True	0	1
module.bert.encoder.layer.6.attention.self.query.bias	True	0	1
module.bert.encoder.layer.6.attention.self.key.weight	True	0	1
module.bert.encoder.layer.6.attention.self.key.bias	True	0	1
module.bert.encoder.layer.6.attention.self.value.weight	True	0	1
module.bert.encoder.layer.6.attention.self.value.bias	True	0	1
module.bert.encoder.layer.6.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.6.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.6.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.6.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.6.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.6.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.6.output.dense.weight	True	0	1
module.bert.encoder.layer.6.output.dense.bias	True	0	1
module.bert.encoder.layer.6.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.6.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.7.attention.self.query.weight	True	0	1
module.bert.encoder.layer.7.attention.self.query.bias	True	0	1
module.bert.encoder.layer.7.attention.self.key.weight	True	0	1
module.bert.encoder.layer.7.attention.self.key.bias	True	0	1
module.bert.encoder.layer.7.attention.self.value.weight	True	0	1
module.bert.encoder.layer.7.attention.self.value.bias	True	0	1
module.bert.encoder.layer.7.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.7.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.7.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.7.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.7.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.7.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.7.output.dense.weight	True	0	1
module.bert.encoder.layer.7.output.dense.bias	True	0	1
module.bert.encoder.layer.7.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.7.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.8.attention.self.query.weight	True	0	1
module.bert.encoder.layer.8.attention.self.query.bias	True	0	1
module.bert.encoder.layer.8.attention.self.key.weight	True	0	1
module.bert.encoder.layer.8.attention.self.key.bias	True	0	1
module.bert.encoder.layer.8.attention.self.value.weight	True	0	1
module.bert.encoder.layer.8.attention.self.value.bias	True	0	1
module.bert.encoder.layer.8.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.8.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.8.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.8.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.8.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.8.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.8.output.dense.weight	True	0	1
module.bert.encoder.layer.8.output.dense.bias	True	0	1
module.bert.encoder.layer.8.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.8.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.9.attention.self.query.weight	True	0	1
module.bert.encoder.layer.9.attention.self.query.bias	True	0	1
module.bert.encoder.layer.9.attention.self.key.weight	True	0	1
module.bert.encoder.layer.9.attention.self.key.bias	True	0	1
module.bert.encoder.layer.9.attention.self.value.weight	True	0	1
module.bert.encoder.layer.9.attention.self.value.bias	True	0	1
module.bert.encoder.layer.9.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.9.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.9.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.9.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.9.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.9.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.9.output.dense.weight	True	0	1
module.bert.encoder.layer.9.output.dense.bias	True	0	1
module.bert.encoder.layer.9.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.9.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.10.attention.self.query.weight	True	0	1
module.bert.encoder.layer.10.attention.self.query.bias	True	0	1
module.bert.encoder.layer.10.attention.self.key.weight	True	0	1
module.bert.encoder.layer.10.attention.self.key.bias	True	0	1
module.bert.encoder.layer.10.attention.self.value.weight	True	0	1
module.bert.encoder.layer.10.attention.self.value.bias	True	0	1
module.bert.encoder.layer.10.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.10.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.10.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.10.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.10.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.10.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.10.output.dense.weight	True	0	1
module.bert.encoder.layer.10.output.dense.bias	True	0	1
module.bert.encoder.layer.10.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.10.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.11.attention.self.query.weight	True	0	1
module.bert.encoder.layer.11.attention.self.query.bias	True	0	1
module.bert.encoder.layer.11.attention.self.key.weight	True	0	1
module.bert.encoder.layer.11.attention.self.key.bias	True	0	1
module.bert.encoder.layer.11.attention.self.value.weight	True	0	1
module.bert.encoder.layer.11.attention.self.value.bias	True	0	1
module.bert.encoder.layer.11.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.11.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.11.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.11.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.11.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.11.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.11.output.dense.weight	True	0	1
module.bert.encoder.layer.11.output.dense.bias	True	0	1
module.bert.encoder.layer.11.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.11.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.12.attention.self.query.weight	True	0	1
module.bert.encoder.layer.12.attention.self.query.bias	True	0	1
module.bert.encoder.layer.12.attention.self.key.weight	True	0	1
module.bert.encoder.layer.12.attention.self.key.bias	True	0	1
module.bert.encoder.layer.12.attention.self.value.weight	True	0	1
module.bert.encoder.layer.12.attention.self.value.bias	True	0	1
module.bert.encoder.layer.12.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.12.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.12.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.12.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.12.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.12.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.12.output.dense.weight	True	0	1
module.bert.encoder.layer.12.output.dense.bias	True	0	1
module.bert.encoder.layer.12.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.12.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.13.attention.self.query.weight	True	0	1
module.bert.encoder.layer.13.attention.self.query.bias	True	0	1
module.bert.encoder.layer.13.attention.self.key.weight	True	0	1
module.bert.encoder.layer.13.attention.self.key.bias	True	0	1
module.bert.encoder.layer.13.attention.self.value.weight	True	0	1
module.bert.encoder.layer.13.attention.self.value.bias	True	0	1
module.bert.encoder.layer.13.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.13.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.13.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.13.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.13.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.13.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.13.output.dense.weight	True	0	1
module.bert.encoder.layer.13.output.dense.bias	True	0	1
module.bert.encoder.layer.13.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.13.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.14.attention.self.query.weight	True	0	1
module.bert.encoder.layer.14.attention.self.query.bias	True	0	1
module.bert.encoder.layer.14.attention.self.key.weight	True	0	1
module.bert.encoder.layer.14.attention.self.key.bias	True	0	1
module.bert.encoder.layer.14.attention.self.value.weight	True	0	1
module.bert.encoder.layer.14.attention.self.value.bias	True	0	1
module.bert.encoder.layer.14.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.14.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.14.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.14.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.14.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.14.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.14.output.dense.weight	True	0	1
module.bert.encoder.layer.14.output.dense.bias	True	0	1
module.bert.encoder.layer.14.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.14.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.15.attention.self.query.weight	True	0	1
module.bert.encoder.layer.15.attention.self.query.bias	True	0	1
module.bert.encoder.layer.15.attention.self.key.weight	True	0	1
module.bert.encoder.layer.15.attention.self.key.bias	True	0	1
module.bert.encoder.layer.15.attention.self.value.weight	True	0	1
module.bert.encoder.layer.15.attention.self.value.bias	True	0	1
module.bert.encoder.layer.15.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.15.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.15.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.15.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.15.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.15.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.15.output.dense.weight	True	0	1
module.bert.encoder.layer.15.output.dense.bias	True	0	1
module.bert.encoder.layer.15.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.15.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.16.attention.self.query.weight	True	0	1
module.bert.encoder.layer.16.attention.self.query.bias	True	0	1
module.bert.encoder.layer.16.attention.self.key.weight	True	0	1
module.bert.encoder.layer.16.attention.self.key.bias	True	0	1
module.bert.encoder.layer.16.attention.self.value.weight	True	0	1
module.bert.encoder.layer.16.attention.self.value.bias	True	0	1
module.bert.encoder.layer.16.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.16.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.16.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.16.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.16.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.16.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.16.output.dense.weight	True	0	1
module.bert.encoder.layer.16.output.dense.bias	True	0	1
module.bert.encoder.layer.16.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.16.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.17.attention.self.query.weight	True	0	1
module.bert.encoder.layer.17.attention.self.query.bias	True	0	1
module.bert.encoder.layer.17.attention.self.key.weight	True	0	1
module.bert.encoder.layer.17.attention.self.key.bias	True	0	1
module.bert.encoder.layer.17.attention.self.value.weight	True	0	1
module.bert.encoder.layer.17.attention.self.value.bias	True	0	1
module.bert.encoder.layer.17.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.17.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.17.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.17.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.17.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.17.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.17.output.dense.weight	True	0	1
module.bert.encoder.layer.17.output.dense.bias	True	0	1
module.bert.encoder.layer.17.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.17.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.18.attention.self.query.weight	True	0	1
module.bert.encoder.layer.18.attention.self.query.bias	True	0	1
module.bert.encoder.layer.18.attention.self.key.weight	True	0	1
module.bert.encoder.layer.18.attention.self.key.bias	True	0	1
module.bert.encoder.layer.18.attention.self.value.weight	True	0	1
module.bert.encoder.layer.18.attention.self.value.bias	True	0	1
module.bert.encoder.layer.18.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.18.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.18.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.18.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.18.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.18.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.18.output.dense.weight	True	0	1
module.bert.encoder.layer.18.output.dense.bias	True	0	1
module.bert.encoder.layer.18.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.18.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.19.attention.self.query.weight	True	0	1
module.bert.encoder.layer.19.attention.self.query.bias	True	0	1
module.bert.encoder.layer.19.attention.self.key.weight	True	0	1
module.bert.encoder.layer.19.attention.self.key.bias	True	0	1
module.bert.encoder.layer.19.attention.self.value.weight	True	0	1
module.bert.encoder.layer.19.attention.self.value.bias	True	0	1
module.bert.encoder.layer.19.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.19.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.19.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.19.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.19.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.19.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.19.output.dense.weight	True	0	1
module.bert.encoder.layer.19.output.dense.bias	True	0	1
module.bert.encoder.layer.19.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.19.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.20.attention.self.query.weight	True	0	1
module.bert.encoder.layer.20.attention.self.query.bias	True	0	1
module.bert.encoder.layer.20.attention.self.key.weight	True	0	1
module.bert.encoder.layer.20.attention.self.key.bias	True	0	1
module.bert.encoder.layer.20.attention.self.value.weight	True	0	1
module.bert.encoder.layer.20.attention.self.value.bias	True	0	1
module.bert.encoder.layer.20.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.20.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.20.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.20.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.20.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.20.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.20.output.dense.weight	True	0	1
module.bert.encoder.layer.20.output.dense.bias	True	0	1
module.bert.encoder.layer.20.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.20.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.21.attention.self.query.weight	True	0	1
module.bert.encoder.layer.21.attention.self.query.bias	True	0	1
module.bert.encoder.layer.21.attention.self.key.weight	True	0	1
module.bert.encoder.layer.21.attention.self.key.bias	True	0	1
module.bert.encoder.layer.21.attention.self.value.weight	True	0	1
module.bert.encoder.layer.21.attention.self.value.bias	True	0	1
module.bert.encoder.layer.21.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.21.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.21.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.21.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.21.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.21.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.21.output.dense.weight	True	0	1
module.bert.encoder.layer.21.output.dense.bias	True	0	1
module.bert.encoder.layer.21.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.21.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.22.attention.self.query.weight	True	0	1
module.bert.encoder.layer.22.attention.self.query.bias	True	0	1
module.bert.encoder.layer.22.attention.self.key.weight	True	0	1
module.bert.encoder.layer.22.attention.self.key.bias	True	0	1
module.bert.encoder.layer.22.attention.self.value.weight	True	0	1
module.bert.encoder.layer.22.attention.self.value.bias	True	0	1
module.bert.encoder.layer.22.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.22.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.22.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.22.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.22.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.22.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.22.output.dense.weight	True	0	1
module.bert.encoder.layer.22.output.dense.bias	True	0	1
module.bert.encoder.layer.22.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.22.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.23.attention.self.query.weight	True	0	1
module.bert.encoder.layer.23.attention.self.query.bias	True	0	1
module.bert.encoder.layer.23.attention.self.key.weight	True	0	1
module.bert.encoder.layer.23.attention.self.key.bias	True	0	1
module.bert.encoder.layer.23.attention.self.value.weight	True	0	1
module.bert.encoder.layer.23.attention.self.value.bias	True	0	1
module.bert.encoder.layer.23.attention.output.dense.weight	True	0	1
module.bert.encoder.layer.23.attention.output.dense.bias	True	0	1
module.bert.encoder.layer.23.attention.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.23.attention.output.LayerNorm.bias	True	0	1
module.bert.encoder.layer.23.intermediate.dense.weight	True	0	1
module.bert.encoder.layer.23.intermediate.dense.bias	True	0	1
module.bert.encoder.layer.23.output.dense.weight	True	0	1
module.bert.encoder.layer.23.output.dense.bias	True	0	1
module.bert.encoder.layer.23.output.LayerNorm.weight	True	0	1
module.bert.encoder.layer.23.output.LayerNorm.bias	True	0	1
module.lm_matcher.lm_predictions.bias	True	0	1 cls.predictions.bias
module.lm_matcher.lm_predictions.transform.dense.weight	True	0	1 cls.predictions.transform.dense.weight
module.lm_matcher.lm_predictions.transform.dense.bias	True	0	1 cls.predictions.transform.dense.bias
module.lm_matcher.lm_predictions.transform.LayerNorm.bias	True	0	1 cls.predictions.transform.LayerNorm.bias
module.lm_matcher.lm_predictions.transform.LayerNorm.weight	True	0	1 cls.predictions.transform.LayerNorm.weight
